In [1]:
import numpy as np

In [2]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [3]:
np.arange(3,5)

array([3, 4])

In [4]:
np.arange(15).reshape(-1,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14]])

In [5]:
np.arange(15).reshape(1,1) #https://stackoverflow.com/questions/18691084/what-does-1-mean-in-numpy-reshape

ValueError: cannot reshape array of size 15 into shape (1,1)

In [6]:
np.arange(15).ndim

1

In [ ]:
#https://numpy.org/doc/stable/user/quickstart.html